apiVersion: v1
items:
  - apiVersion: v1
    kind: Service
    metadata:
      annotations:
        service.alpha.openshift.io/dependencies: '[{"name": "${DATABASE_SERVICE_NAME}", "namespace": "", "kind": "Service"}]'
      name: bg-blue
    spec:
      ports:
      - name: web
        port: 8080
        targetPort: 8080
      selector:
        name: bg-blue
  - apiVersion: v1
    kind: Service
    metadata:
      annotations:
        service.alpha.openshift.io/dependencies: '[{"name": "${DATABASE_SERVICE_NAME}", "namespace": "", "kind": "Service"}]'
      name: bg-green
    spec:
      ports:
      - name: web
        port: 8080
        targetPort: 8080
      selector:
        name: bg-green
  - apiVersion: v1
    kind: Route
    metadata:
      name: blue-bg
    spec:
      to:
        kind: Service
        name: bg-blue
  - apiVersion: v1
    kind: Route
    metadata:
      name: green-bg
    spec:
      to:
        kind: Service
        name: bg-green
  - apiVersion: v1
    kind: Route
    metadata:
      name: bg
    spec:
      alternateBackends:
      - name: bg-green
        weight: "0"
      to:
        kind: Service
        name: bg-blue
        weight: "100"
kind: List
metadata: {}
